function Du = DuFun(in1,hh1,y01)
%DUFUN
%    DU = DUFUN(IN1,HH1,Y01)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    08-Sep-2021 07:54:16

x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
t2 = cos(y01);
t3 = sin(y01);
t4 = x6.*4.0;
t5 = x7.*4.0;
t6 = x4.^2;
t7 = x5.^2;
t8 = x6.^2;
t9 = x7.^2;
t10 = x4.*x7.*2.0;
t11 = x5.*x6.*2.0;
